name: 'dbt_practice'
version: '1.0.0'

profile: 'dbt_practice'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: 
  - "target"
  - "dbt_packages"

models:
  dbt_practice:
  +meta:
    owner: "sql_file_owner@gmail.com"
    year_created: 2025

seeds:
  dbt_course_practice:
    schema: seeds